import { StyleSheet } from 'react-native';

export const colors = {
  background: '#FFF9F1',
  surface: '#FFFFFF',
  ink: '#321B13',
  muted: '#84685A',
  red: '#96351F',
  orange: '#D96025',
  gold: '#F6C968',
  pale: '#FFF0DA',
  border: '#ECD7C7',
  green: '#3B7652',
};

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  page: { flex: 1 },
  content: { paddingHorizontal: 18, paddingTop: 12, paddingBottom: 28 },
  loginContent: { flexGrow: 1, justifyContent: 'center', padding: 24, paddingBottom: 60 },
  loginBrand: { alignItems: 'center', marginBottom: 28 },
  loginLogoImage: { width: 116, height: 116, borderRadius: 24 },
  loginBrandName: { color: colors.red, fontSize: 30, fontWeight: '900', letterSpacing: 1.2, marginTop: 12 },
  loginTagline: { color: colors.muted, fontSize: 14, marginTop: 4 },
  loginCard: { backgroundColor: '#FFF9F4', borderRadius: 24, padding: 22, borderWidth: 1, borderColor: '#F0DED1' },
  loginTitle: { color: colors.ink, fontSize: 23, fontWeight: '700', marginBottom: 8 },
  loginBody: { color: colors.muted, fontSize: 14, lineHeight: 21, marginBottom: 18 },
  loginSwitch: { color: colors.orange, textAlign: 'center', fontWeight: '600', marginTop: 16 },
  authMessage: { color: colors.red, fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 14 },
  authLoading: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16, padding: 24 },
  signedInAs: { color: colors.muted, fontSize: 11, marginBottom: 10 },
  authModeRow: { flexDirection: 'row', gap: 8, marginBottom: 6 },
  authMode: { flex: 1, minHeight: 44, borderRadius: 13, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface },
  authModeActive: { borderColor: colors.red, backgroundColor: colors.pale },
  authModeText: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  authModeTextActive: { color: colors.red, fontWeight: '900' },
  phoneRow: { flexDirection: 'row', gap: 8 },
  phonePrefix: { width: 62, minHeight: 52, borderWidth: 1, borderColor: colors.border, borderRadius: 15, backgroundColor: colors.pale, alignItems: 'center', justifyContent: 'center' },
  phonePrefixText: { color: colors.red, fontSize: 15, fontWeight: '900' },
  phoneInput: { flex: 1, minHeight: 52, borderWidth: 1, borderColor: colors.border, borderRadius: 15, paddingHorizontal: 15, color: colors.ink, fontSize: 15, backgroundColor: colors.surface },
  otpInput: { textAlign: 'center', letterSpacing: 8, fontSize: 20, fontWeight: '900' },
  header: { flexDirection: 'row', alignItems: 'center', minHeight: 46, marginBottom: 15 },
  logo: { width: 42, height: 42, borderRadius: 13, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  logoImage: { width: 42, height: 42 },
  headerCopy: { flex: 1, marginLeft: 10 },
  headerTitle: { color: colors.ink, fontSize: 18, fontWeight: '900' },
  headerSubtitle: { color: colors.muted, fontSize: 10, marginTop: 2 },
  avatar: { width: 38, height: 38, borderRadius: 20, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: colors.red, fontWeight: '800' },
  back: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  backText: { color: colors.ink, fontSize: 34, lineHeight: 35 },
  date: { color: colors.muted, fontSize: 12, marginBottom: 14 },
  dateStrong: { color: colors.ink, fontWeight: '800' },
  hero: { minHeight: 202, borderRadius: 24, padding: 20, backgroundColor: colors.orange, overflow: 'hidden' },
  eyebrow: { color: '#FFE4D4', fontSize: 10, fontWeight: '900', letterSpacing: 1.2 },
  heroTitle: { color: colors.surface, fontSize: 28, fontWeight: '900', marginTop: 8 },
  heroBody: { color: '#FFF2EB', fontSize: 13, lineHeight: 20, marginTop: 5, maxWidth: 270 },
  heroButton: { alignSelf: 'flex-start', marginTop: 18, borderRadius: 14, paddingHorizontal: 15, paddingVertical: 12, backgroundColor: colors.gold },
  heroButtonText: { color: '#642410', fontSize: 13, fontWeight: '900' },
  om: { position: 'absolute', right: 14, bottom: -29, color: 'rgba(255,255,255,0.14)', fontSize: 96, fontWeight: '800' },
  section: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 20, marginBottom: 10 },
  sectionTitle: { color: colors.ink, fontSize: 15, fontWeight: '900' },
  sectionLink: { color: '#A35D3B', fontSize: 11, fontWeight: '700' },
  columns: { flexDirection: 'row', gap: 10 },
  poojaCard: { flex: 1, minHeight: 153, borderWidth: 1, borderColor: colors.border, borderRadius: 19, padding: 14, backgroundColor: colors.surface },
  poojaCardPhoto: { width: 54, height: 54, borderRadius: 12, marginBottom: 8 },
  highlight: { borderColor: colors.gold, backgroundColor: '#FFFBEF' },
  emoji: { fontSize: 26, marginBottom: 8 },
  cardTitle: { color: colors.ink, fontSize: 14, fontWeight: '900' },
  cardBody: { color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 4 },
  tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 10 },
  tag: { color: '#8D462A', backgroundColor: '#FFF3E4', paddingHorizontal: 7, paddingVertical: 4, borderRadius: 7, fontSize: 9 },
  rowCard: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 13, marginBottom: 10, backgroundColor: colors.surface },
  quickControls: { gap: 9, marginTop: 12 },
  audioControl: { flexDirection: 'row', alignItems: 'center', borderRadius: 18, padding: 12, backgroundColor: '#FFF2DC', borderWidth: 1, borderColor: colors.gold },
  reminderCard: { flexDirection: 'row', alignItems: 'center', borderRadius: 18, padding: 12, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  controlIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFE1B3', marginRight: 11 },
  controlIconText: { color: colors.red, fontSize: 20, fontWeight: '900' },
  miniPlay: { width: 34, height: 34, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.red },
  miniPlayOn: { backgroundColor: colors.green },
  miniPlayText: { color: colors.surface, fontSize: 13, fontWeight: '900' },
  featureCard: { flexDirection: 'row', alignItems: 'center', borderRadius: 20, padding: 15, marginBottom: 4, backgroundColor: '#FFF1D8', borderWidth: 1, borderColor: colors.gold },
  compactRow: { minHeight: 55, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#EEDFD3', backgroundColor: colors.surface, paddingHorizontal: 11 },
  dayBadge: { width: 38, color: colors.red, fontSize: 10, fontWeight: '900', textTransform: 'uppercase' },
  listEmoji: { width: 34, fontSize: 19 },
  dayPhoto: { width: 30, height: 30, borderRadius: 8, marginRight: 4 },
  listTitle: { flex: 1, color: colors.ink, fontSize: 13, fontWeight: '800' },
  icon: { width: 48, height: 48, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.pale, marginRight: 12 },
  iconPhoto: { width: 48, height: 48, borderRadius: 15 },
  iconText: { fontSize: 24 },
  grow: { flex: 1 },
  chevron: { color: colors.orange, fontSize: 25, marginLeft: 8 },
  intro: { color: colors.muted, fontSize: 12, marginBottom: 14 },
  panchangam: { borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 16, backgroundColor: colors.surface },
  panchangamTitle: { color: colors.ink, fontSize: 16, fontWeight: '900' },
  monthHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14, paddingHorizontal: 5 },
  monthArrow: { color: colors.red, fontSize: 32, paddingHorizontal: 12 },
  monthTitle: { color: colors.ink, textAlign: 'center', fontSize: 20, fontWeight: '900' },
  monthSubtitle: { color: colors.orange, textAlign: 'center', fontSize: 11, fontWeight: '700', marginTop: 3 },
  calendarCard: { borderRadius: 22, padding: 10, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  calendarCell: { width: '14.2857%', height: 47, alignItems: 'center', justifyContent: 'center' },
  weekDay: { color: colors.muted, fontSize: 10, fontWeight: '900', textTransform: 'uppercase' },
  dateCircle: { width: 38, height: 38, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  dateSelected: { backgroundColor: colors.red },
  dateNumber: { color: colors.ink, fontSize: 13, fontWeight: '700' },
  dateNumberSelected: { color: colors.surface, fontWeight: '900' },
  festivalDot: { position: 'absolute', bottom: 3, width: 5, height: 5, borderRadius: 3, backgroundColor: colors.orange },
  festivalDotSelected: { backgroundColor: colors.gold },
  calendarHint: { color: colors.muted, fontSize: 10, textAlign: 'center', marginTop: 10, marginBottom: 13 },
  expandedDate: { flexDirection: 'row', alignItems: 'center', borderRadius: 20, padding: 14, backgroundColor: '#FFF1D8', borderWidth: 1, borderColor: colors.gold },
  selectedDateBadge: { width: 52, height: 58, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.red, marginRight: 12 },
  selectedDateNumber: { color: colors.surface, fontSize: 22, fontWeight: '900' },
  selectedDateMonth: { color: '#FFD9C8', fontSize: 9, fontWeight: '800' },
  expandedTithi: { color: colors.ink, fontSize: 13, fontWeight: '900' },
  calendarPooja: { color: colors.red, fontSize: 11, fontWeight: '800', marginTop: 7 },
  smallStart: { borderRadius: 11, backgroundColor: colors.red, paddingHorizontal: 12, paddingVertical: 9, marginLeft: 7 },
  smallStartText: { color: colors.surface, fontSize: 10, fontWeight: '900' },
  legend: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 15 },
  legendDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.orange, marginRight: 7 },
  deity: { width: 92, height: 92, borderRadius: 30, alignSelf: 'center', alignItems: 'center', justifyContent: 'center', marginTop: 4, backgroundColor: colors.gold },
  deityPhoto: { width: 92, height: 92, borderRadius: 30 },
  deityText: { fontSize: 47 },
  centerTitle: { color: colors.ink, textAlign: 'center', fontSize: 22, fontWeight: '900', marginTop: 14 },
  centerBody: { color: colors.muted, textAlign: 'center', fontSize: 11, marginTop: 5 },
  progress: { height: 7, borderRadius: 10, backgroundColor: '#EEDFD3', marginTop: 20, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 10, backgroundColor: colors.orange },
  checkRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: '#F0E2D8' },
  samagriGroup: { color: colors.red, fontSize: 13, fontWeight: '900', marginTop: 22, marginBottom: 2 },
  samagriPicture: { width: 40, height: 40, borderRadius: 12, backgroundColor: colors.pale, alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  samagriPictureText: { fontSize: 22 },
  samagriImage: { width: '100%', height: '100%', borderRadius: 8 },
  samagriPictureSmall: { width: 25, height: 25, borderRadius: 8, backgroundColor: colors.pale, alignItems: 'center', justifyContent: 'center', marginRight: 5 },
  checkbox: { width: 21, height: 21, borderRadius: 6, borderWidth: 1.5, borderColor: '#CCAA96', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  checkboxOn: { backgroundColor: colors.red, borderColor: colors.red },
  checkmark: { color: colors.surface, fontWeight: '900', fontSize: 13 },
  checkText: { color: colors.ink, fontSize: 13, flex: 1 },
  button: { flex: 1, minHeight: 48, borderRadius: 15, backgroundColor: colors.red, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14, marginTop: 18 },
  buttonText: { color: colors.surface, fontWeight: '900', fontSize: 13, textAlign: 'center' },
  secondary: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  secondaryText: { color: colors.red },
  pressed: { opacity: 0.72, transform: [{ scale: 0.99 }] },
  price: { color: colors.red, textAlign: 'center', fontSize: 35, fontWeight: '900', marginTop: 15 },
  plan: { flexDirection: 'row', alignItems: 'center', borderWidth: 2, borderColor: colors.border, borderRadius: 18, padding: 15, marginTop: 11, backgroundColor: colors.surface },
  planSelected: { borderColor: colors.red, backgroundColor: '#FFF8E7' },
  planPrice: { color: colors.red, fontSize: 17, fontWeight: '900', marginLeft: 12 },
  note: { color: colors.muted, fontSize: 9, textAlign: 'center', marginTop: 10 },
  guideTop: { alignItems: 'flex-end' },
  audioRing: { width: 184, height: 184, borderRadius: 100, alignSelf: 'center', alignItems: 'center', justifyContent: 'center', marginTop: 25, borderWidth: 18, borderColor: '#FFF0D9', backgroundColor: '#FFE1A0' },
  playCircle: { width: 74, height: 74, borderRadius: 40, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.red },
  playText: { color: colors.surface, fontSize: 29, fontWeight: '900' },
  mantraCard: { alignItems: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: 20, padding: 20, marginTop: 18, backgroundColor: colors.surface },
  mantraName: { color: colors.ink, fontSize: 18, lineHeight: 31 },
  mantraStrong: { color: colors.red, fontSize: 19, lineHeight: 31, fontWeight: '900', textAlign: 'center' },
  instruction: { color: colors.muted, textAlign: 'center', fontSize: 12, lineHeight: 19, marginHorizontal: 12, marginTop: 15 },
  guideButtons: { flexDirection: 'row', gap: 10 },
  previous: { color: colors.muted, textAlign: 'center', fontSize: 12, marginTop: 17 },
  poojaSession: { flexDirection: 'row', gap: 10, alignItems: 'flex-start' },
  samagriPanel: { flex: 1.15, borderRadius: 20, padding: 13, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  audioPanel: { flex: 0.85, minHeight: 285, borderRadius: 20, padding: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF1D8', borderWidth: 1, borderColor: colors.gold },
  panelEyebrow: { color: colors.red, fontSize: 9, fontWeight: '900', letterSpacing: 0.8, marginBottom: 11 },
  samagriGroupMini: { color: colors.red, fontSize: 9, fontWeight: '900', marginTop: 8, marginBottom: 7 },
  samagriMiniRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  samagriNumber: { width: 22, height: 22, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.pale, marginRight: 7 },
  samagriNumberText: { color: colors.red, fontSize: 9, fontWeight: '900' },
  samagriMiniText: { flex: 1, color: colors.ink, fontSize: 9, lineHeight: 13, fontWeight: '700' },
  audioOm: { color: colors.orange, fontSize: 50, lineHeight: 62, marginBottom: 13 },
  guideDeityPhoto: { width: 112, height: 112, borderRadius: 18, marginBottom: 13 },
  sessionPlay: { width: 62, height: 62, borderRadius: 32, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.red },
  sessionPlayText: { color: colors.surface, fontSize: 24, fontWeight: '900' },
  audioState: { color: colors.muted, fontSize: 10, fontWeight: '700', marginTop: 10 },
  audioSeekArea: { height: 34, justifyContent: 'center', marginTop: 10, cursor: 'pointer' },
  audioProgress: { height: 6, borderRadius: 6, overflow: 'hidden', backgroundColor: '#EEDFD3' },
  audioProgressFill: { height: '100%', borderRadius: 6, backgroundColor: colors.orange },
  audioTimeRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 5 },
  audioTime: { color: colors.muted, fontSize: 12 },
  speedRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12 },
  speedLabel: { color: colors.muted, fontSize: 13, marginRight: 4 },
  speedButton: { borderWidth: 1, borderColor: '#E4D2C6', borderRadius: 14, paddingVertical: 5, paddingHorizontal: 10 },
  speedButtonActive: { backgroundColor: colors.orange, borderColor: colors.orange },
  speedButtonText: { color: colors.ink, fontSize: 12 },
  speedButtonTextActive: { color: '#FFFFFF' },
  subtitleCard: { minHeight: 112, borderRadius: 18, padding: 17, marginTop: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#321B13' },
  subtitleLabel: { color: colors.gold, fontSize: 9, fontWeight: '900', letterSpacing: 1.1, marginBottom: 9 },
  subtitleText: { color: colors.surface, fontSize: 15, lineHeight: 23, textAlign: 'center', fontWeight: '700' },
  personalizedNote: { color: colors.muted, fontSize: 10, textAlign: 'center', marginTop: 10 },
  inputLabel: { color: colors.muted, fontSize: 11, fontWeight: '800', marginTop: 14, marginBottom: 6 },
  input: { minHeight: 52, borderWidth: 1, borderColor: colors.border, borderRadius: 15, paddingHorizontal: 15, color: colors.ink, fontSize: 15, backgroundColor: colors.surface },
  profileSectionTitle: { color: colors.ink, fontSize: 16, fontWeight: '900', marginTop: 5 },
  familyHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 25, marginBottom: 11 },
  familyHelp: { color: colors.muted, fontSize: 10, marginTop: 3 },
  memberCount: { minWidth: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.pale },
  memberCountText: { color: colors.red, fontSize: 12, fontWeight: '900' },
  emptyFamily: { alignItems: 'center', justifyContent: 'center', borderRadius: 17, borderWidth: 1, borderStyle: 'dashed', borderColor: colors.border, padding: 18, backgroundColor: 'rgba(255,255,255,0.55)' },
  emptyFamilyIcon: { color: '#B58E77', fontSize: 25 },
  emptyFamilyText: { color: colors.muted, fontSize: 11, marginTop: 5 },
  familyRow: { minHeight: 55, flexDirection: 'row', alignItems: 'center', borderRadius: 15, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, paddingHorizontal: 10, marginBottom: 8 },
  familyAvatar: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.pale, marginRight: 8 },
  familyAvatarText: { color: colors.red, fontSize: 13, fontWeight: '900' },
  familyNameInput: { flex: 1, minHeight: 48, color: colors.ink, fontSize: 13, fontWeight: '700' },
  removeMember: { width: 31, height: 31, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF0EA' },
  removeMemberText: { color: colors.red, fontSize: 21, lineHeight: 22 },
  addFamilyRow: { flexDirection: 'row', gap: 8, marginTop: 2 },
  addFamilyInput: { flex: 1, minHeight: 49, borderRadius: 15, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, color: colors.ink, fontSize: 12, paddingHorizontal: 13 },
  addMemberButton: { minWidth: 75, minHeight: 49, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.red, paddingHorizontal: 12 },
  addMemberButtonText: { color: colors.surface, fontSize: 12, fontWeight: '900' },
  verified: { flexDirection: 'row', alignItems: 'center', borderRadius: 17, padding: 14, marginTop: 18, backgroundColor: '#EEF7F0' },
  verifiedIcon: { width: 34, height: 34, borderRadius: 18, color: colors.surface, backgroundColor: colors.green, textAlign: 'center', lineHeight: 34, fontWeight: '900', marginRight: 12 },
  nav: { height: 74, flexDirection: 'row', paddingTop: 8, paddingBottom: 4, borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: colors.surface },
  navItem: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  navIcon: { color: '#9B7D6D', fontSize: 19 },
  navLabel: { color: '#9B7D6D', fontSize: 9, marginTop: 3 },
  navActive: { color: colors.red, fontWeight: '900' },
});
